### ISSUE TITLE
[Suggestion]: Configurable empty hotbar slot sound

### ISSUE THREAD

**Issue by mosharky** [Arborsm/ExtraSoundsForge#11]
I'd like to toggle the empty hotbar scroll sound alone without touching other hotbar sounds

**Comment by Arborsm** [comment]
wdym, the empty hotbar scroll sound volume?

**Comment by mosharky** [comment]
If you don't have an item on a hotbar slot, when you switch to that slot it makes a specific sound

**Comment by Arborsm** [comment]
> If you don't have an item on a hotbar slot, when you switch to that slot it makes a specific sound

I know, what do you want,turn it off or something?

**Comment by mosharky** [comment]
Yes in the config

**Comment by Arborsm** [comment]
> Yes in the config

hm maybe add it later
