### ISSUE TITLE
Crash when using a bow

### ISSUE THREAD

**Issue by CanQtop1gg** [Arborsm/ExtraSoundsForge#16]
[crash-2024-03-13_23.48.10-client.txt](https://github.com/Arborsm/ExtraSoundsForge/files/14593835/crash-2024-03-13_23.48.10-client.txt)

It's just that using any bow crashes

**Comment by Arborsm** [comment]
hm,gonna fix it next version

**Comment by Arborsm** [comment]
I'm not sure why it happens, and could you try this? https://github.com/Arborsm/ExtraSoundsForge/releases/tag/1.2c-hf-1.19.2

**Comment by CanQtop1gg** [comment]
> I'm not sure why it happens, and could you try this? https://github.com/Arborsm/ExtraSoundsForge/releases/tag/1.2c-hf-1.19.2

That really solved the problem. No more crashing when using the bow

**Comment by CanQtop1gg** [comment]
> I'm not sure why it happens, and could you try this? https://github.com/Arborsm/ExtraSoundsForge/releases/tag/1.2c-hf-1.19.2

When will you release the version to the public? I need to update the version in my modpack

**Comment by Arborsm** [comment]
today or tomorrow

**Comment by Arborsm** [comment]
Processing
