### ISSUE TITLE
[Suggestion] [Mod-Compatibility]: Use Auditory Block Sounds instead of Vanilla

### ISSUE THREAD

**Issue by AmazeingGames** [Arborsm/ExtraSoundsForge#19]
Hello! I'm really enjoying this mod along with some other immersion-esque mods, namely [Auditory](https://legacy.curseforge.com/minecraft/mc-mods/auditory), a forge port of a fabric mod of the same name, which replaces vanilla block placement, walk, and break sounds to be unique for many different types (iron ore sounds different from cobblestone, for example), demonstration [here](https://www.youtube.com/watch?embeds_referring_euri=https%3A%2F%2Flegacy.curseforge.com%2F&source_ve_path=Mjg2NjQsMjg2NjQsMTY0NTAz&feature=emb_share&v=M8XXMR446eY) and [here](https://youtu.be/9flfX_Zf5mk?si=IfttKeK0Kk2LSWzJ&t=185). Your mod has a feature where grabbing, dropping, and moving around items in your inventory plays the footstep sound of that block, and it'd be just perfect if these two mods were compatible, in that it would grab the sound used by the auditory mod, instead of the vanilla version.

Thank you for reading! I hope this feature isn't too big an ask, but I appreciate the hard-work all modders do regardless!

Best, 

Amazeing

**Comment by Arborsm** [comment]
Not considered for now
