### ISSUE TITLE
Items occasionally do not make the correct sound when being picked up.

### ISSUE THREAD

**Issue by MidasMischief** [Arborsm/ExtraSoundsForge#2]
Pretty minor bug all things considered, but every now and then when picking up certain items, namely cod, salmon or pufferfish, it will make a stone pickup sound instead of the usual fish pickup sound.

**Comment by Arborsm** [comment]
soon fix it

**Comment by Arborsm** [comment]
hmm, the original mod is this sound, and I'm not good at sound effects, lol
