### ISSUE TITLE
Latest version of 1.19.2 crashes with Carryon + Solution to #15

### ISSUE THREAD

**Issue by Tosh022402** [Arborsm/ExtraSoundsForge#21]
Using the latest version of Carryon and ExtraSounds Crashes my game, however downgrading to the hotfix version 1.2c-1.19.2 works fine.

Also for issue #15  figured out that there is like a small howling sound whenever you gain/remove a potion effect, so whenever you carry an entity using carryon it constantly gives you the slowness effect, thats why that howling sound keeps playing so often. The solution would be either disabling the "Effect Sounds" from Extra Sounds, or disabling the "slowness multiplier" on Carryon´s configs

**Comment by Arborsm** [comment]
I know it, there just some code issue gonna fix it
