### ISSUE TITLE
Compatibility issue with "Carry On"

### ISSUE THREAD

**Issue by AmongUsIsSus** [Arborsm/ExtraSoundsForge#23]
Before I write my very minor bug report, I'd like to congratulate and appreciate your wonderful work on adding a port to forge with this satisfying sound mod. The best of the best, especially in terms of inventory enjoyment.

The issue is that when picking up entities or blocks with the well-renowned "Carry On" mod, it will constantly play the sound(s):

extrasounds:entity.remove.negative
extrasounds:entity.add.negative

This sound for some reason can be described as the ambient portal sounds, it doesn't exactly sound like a sound constantly cutting off and restarting, but merely like I said the portal ambience for the Nether portal. I have no clue why, an idea I thought of was to add configs to be able to toggle specific sounds and post the sound library with a "true" and "false" answer!

When I used "OmegaMute" and did the command to listen, this sound file would constantly spam only after picking up a block.
![image](https://github.com/Arborsm/ExtraSoundsForge/assets/82697341/0c88891b-f1e5-475e-bc1b-6090111e2f5e)

Thank you for your time!

**Comment by Arborsm** [comment]
Actually, since https://github.com/Arborsm/ExtraSoundsForge/commit/53b80c8d26e554220026594339e4adee00aec9a5, the effect sound is disable by default because mods have too many conflict behavior，btw is the `entity` in `extrasounds:entity.remove.negative` your typing wrong or?
