### ISSUE TITLE
ExtraSound settings are not saved

### ISSUE THREAD

**Issue by xleb-normal** [Arborsm/ExtraSoundsForge#33]
When re-entering ExtraSound settings, Item drop, Empty Hotbar, Footstep, Effects, Poof parameters do not save the changed values, but are reset to default values, but the sliders work properly

**Comment by meitastic** [comment]
I am experiencing the same issue, changing any of the on/off settings does not work, they revert to their original values immediately after leaving the extra sounds menu, i have experienced this on 1.20.1 fabric

this mod is pretty excellent with its sounds, i love them

**Comment by Arborsm** [comment]
well it did save but it doesn't change ui, ok I wil fix it soon
