### ISSUE TITLE
1.21.1 NeoForge crash when opening inventory

### ISSUE THREAD

**Issue by Daltaxy** [Arborsm/ExtraSoundsForge#35]
not much to say, it crashes without exception when opening the inventory.
latest NeoForge version

`Fatal: Mixin apply for mod extrasounds failed`
https://mclo.gs/LLayuDN#L3632

probably caused/linked by JEI update?

**Comment by RoboXGamer** [comment]
yes according to the JEI version this code shows it is very old
so JEI is not compatible with this till the mod updates

**Comment by RoboXGamer** [comment]
mine is crashing on world load

**Comment by RoboXGamer** [comment]
Thank you for keeping this mod updated
I am very much in love with the sounds for inventory and dropping mostly but it makes Minecraft fun for me!
